library(fda)
library(Deriv)
library(MASS)
# library(tidyverse)
# library(R.utils)
# 
# sourceDirectory("Data")
# sourceDirectory("FNN")

source('Data/gdata.R')
source('Data/data_input.R')
source('Data/fun_output.R')
source('Data/data_output.R')
# # source('Data/f2n.R')
# source("LM/flm.R")
# source("LM/flm2.R")

source('FNN/f2m.R')
source('FNN/cost.R')
source('FNN/fnn_p.R')
source('FNN/init.R')
source('FNN/prop.R')
source('FNN/pen.R')

source('Common/common.R')
source('Common/divide.R')