real <- function(seed, HL = 1) {
  vari. <- c("method", "train", "test", "mse1", "mse2")
  ipath <- paste0("../4_Output/Real1/", seed, ".csv")
  library(MASS)
  library(fda)
  library(Deriv)
  source('Common/common.R')
  source('Common/divide.R')
  Output.(rbind(vari.), ipath)
  X <- read.csv(paste0("../Data/Real1/x.csv"), row.names = 1)
  G <- read.csv(paste0("../Data/Real1/g.csv"), row.names = 1)
  Y <- read.csv(paste0("../Data/Real1/y.csv"), row.names = 1)
  POS <- as.numeric(substring(colnames(G), 2))
  pos <- (POS - min(POS))/(max(POS) - min(POS))
  X[, "age_int"] <- (X[, "age_int"] - 13)/70
  Y <- log(as.numeric(Y$Y) + 1)
  Y <- as.matrix((Y - mean(Y))/sd(Y))
  X <- as.matrix(X)
  G <- as.matrix(G)
  groups <- divide(1:nrow(Y), seed)
  list2env(sep(mget(c('Y', 'X', 'G')), groups), envir = environment())
  Output.(rbind(vari.), ipath)
  if (!("FLM1" %in% (read.csv(ipath)$method))) {
    source("LM/flm.R")
    bb0 <- create.bspline.basis(norder = 4, nbasis = 8)
    flm1.p <- flm1(Y.train, G.train, bb0, pos, X.train, lambda. = c(10^(-1:3)))
    Y.train. <- pred.flm1(G.train, bb0, pos, flm1.p$para, X.train)
    Y.test. <- pred.flm1(G.test, bb0, pos, flm1.p$para, X.test)
    error <- Error(Y.train, Y.test, Y.train., Y.test.)
    prt(format(cbind(error, method = "FLM1")[, vari.], digits = 4), ipath)
  }
  if (!(paste0("NN", HL) %in% (read.csv(ipath)$method))) {
    source("NN/cost.R")
    source("NN/nn_p.R")
    source("NN/prop.R")
    source("NN/init.R")
    source("NN/update.R")
    A <- c(rep(list(sigmoid), HL), list(linear))
    E.train <- cbind(X.train, G.train)
    E.test <- cbind(X.test, G.test)
    Bases <- c(list(ncol(E.train)), as.list(rep(8, HL)), list(1))
    nn.p <- NN.p(Y.train, E.train, Bases, A = A, lambda. = 10^(-1:3))
    # nn.p <- NN.p(Y.train, E.train, Bases, A = A, lambda. = 0)
    Y.train. <- pred(nn.p$Ac, E.train, A)
    Y.test. <- pred(nn.p$Ac, E.test, A)
    error <- Error(Y.train, Y.test, Y.train., Y.test.)
    prt(format(cbind(error, method = paste0("NN", HL))[, vari.], digits = 4),
        ipath)
  }
  if (!(paste0("FN", HL) %in% (read.csv(ipath)$method))) {
    source('FNN/f2m.R')
    source('FNN/cost.R')
    source('FNN/fnn_p.R')
    source('FNN/init.R')
    source('FNN/prop.R')
    source('FNN/pen.R')
    .bb <- create.bspline.basis(norder = 4, nbasis = 8)
    A <- c(rep(list(sigmoid), HL), list(linear))
    Bases <- c(list(.bb), rep(list(.bb), HL), list(.bb))
    loc.train <- as.matrix(X.train[, "age_int"])
    loc.test <- as.matrix(X.test[, "age_int"])
    Y.train <- cbind(Y.train, loc.train)
    Y.test <- cbind(Y.test, loc.test)
    rownames(Y.train) <- rownames(G.train)
    rownames(Y.test) <- rownames(G.test)
    X.train <- X.train[, c("race", "sex")]
    X.test <- X.test[, c("race", "sex")]
    fnn.p <- FNN.p(Y.train, X.train, G.train, Bases, A, lambda.=10^(-1:3), pos)
    Y.train. <- pred(fnn.p$Ac, X.train, G.train, A, Bases, pos, loc.train)
    Y.test. <- pred(fnn.p$Ac, X.test, G.test, A, Bases, pos, loc.test)
    error <- Error(Y.train[, 1, drop = FALSE], Y.test[, 1, drop = FALSE],
                   Y.train., Y.test.)
    prt(format(cbind(error, method = paste0("FN", HL))[, vari.], digits = 4),
        ipath)
  }
  print(read.csv(ipath), row.names = FALSE)
}